name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          resources: |
            - name: observe_monitor
              attributes:
                - name
                - description
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version-file: go.mod
          cache: true
      - run: go test -v ./...